# Generated by Django 5.0.7 on 2024-07-29 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0008_alter_livre_image_alter_livre_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='library',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='library',
            name='is_staff',
        ),
        migrations.AddField(
            model_name='library',
            name='is_logged_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterModelTable(
            name='library',
            table='Librairies',
        ),
        migrations.AlterModelTable(
            name='livre',
            table='Livres',
        ),
    ]
