# Generated by Django 5.0.7 on 2024-07-29 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0009_remove_library_is_active_remove_library_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='library',
            name='is_logged_in',
        ),
    ]
