# Generated by Django 5.0 on 2024-07-30 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0010_remove_library_is_logged_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='C:\\Users\\DELL\\Pictures\\Gestion-des-librairies\\Django project\\lib\\static\\Photos'),
        ),
    ]
