# Generated by Django 5.0 on 2024-07-30 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0011_library_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='library',
            name='images',
        ),
        migrations.AddField(
            model_name='library',
            name='champ_activation',
            field=models.BooleanField(default=False),
        ),
    ]
