# Generated by Django 5.0 on 2024-07-31 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0017_alter_livre_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livre',
            name='status',
            field=models.CharField(default='disponible', max_length=100, null=True),
        ),
    ]
