# Generated by Django 5.0 on 2024-07-31 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0020_alter_library_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='library',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
