# Generated by Django 5.0 on 2024-07-31 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0021_library_latitude_library_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='library',
            name='last_login',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='library',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='library',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
