# Generated by Django 5.0 on 2024-07-31 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0022_library_date_joined_alter_library_last_login_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
